version: "3"
services:
  app:
    container_name: hyperzod-tenant-svc
    build:
      dockerfile: ./docker/Dockerfile
      args:
        - ENV=${APP_ENV}
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 8002:8000
    volumes:
      - ".:/var/www/html"
networks:
  default:
    external: true
    name: hyperzod-network
