#!/bin/sh

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

if [ ! -d /var/log/supervisor ]; then
    mkdir /var/log/supervisor
fi

chmod -R ugo+rw /.composer

# check if vendor/autoload.php exists
if [ ! -f vendor/autoload.php ]; then
    composer install
fi

# check if node_modules/ exists
if [ ! -d node_modules ]; then
    npm install
fi

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
